name: Deploy to EC2 and Run Tests

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Replace with your project's Ruby version
          bundler-cache: true

      # Step 3: Fix permissions for Brakeman
      - name: Fix permissions for Brakeman
        run: chmod +x bin/brakeman

      # Step 4: Run Brakeman for security checks
      - name: Run Brakeman security checks
        run: |
          bin/brakeman --no-pager || echo "Brakeman failed but allowing pipeline to proceed"

      # Step 5: Set up SSH agent for EC2 deployment
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSHPRIVATE }}

      # Step 6: Deploy to EC2 instance
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.91.216.27 << 'EOF'
          # Navigate to the project directory
          cd ~/cloudproject || exit

          # Pull the latest changes from the repository
          git pull origin main

          # Install dependencies
          bundle install --deployment --without development test

          # Precompile assets for production
          rails assets:precompile RAILS_ENV=production

          # Run database migrations
          rails db:migrate RAILS_ENV=production

          # Restart the Rails server
          sudo systemctl restart puma
          EOF
