name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up SSH agent
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSHPRIVATE }}

      # Step 3: Set executable permissions for Brakeman
      - name: Set executable permissions for Brakeman
        run: chmod +x bin/brakeman

      # Step 4: Run Brakeman for security analysis
      - name: Run Brakeman security checks
        run: bin/brakeman --no-pager

      # Step 5: Deploy application to EC2
      - name: Deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.91.216.27 << EOF
          cd cloudproject
          git pull origin main
          bundle install
          rails db:migrate RAILS_ENV=production
          rails assets:precompile RAILS_ENV=production
          sudo systemctl restart puma
          EOF
