name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Install Ruby and gems
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.2 # Use a compatible Ruby version
          bundler-cache: true

      # Step 2: Fix permissions for Rails scripts
      - name: Fix permissions for Rails scripts
        run: chmod +x bin/*

      # Step 3: Set up database schema
      - name: Set up database schema
        run: bin/rails db:schema:load

      # Step 4: Run tests
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1: Install Ruby and gems
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.2 # Use a compatible Ruby version
          bundler-cache: true

      # Step 2: Fix permissions for Rails scripts
      - name: Fix permissions for Rails scripts
        run: chmod +x bin/*

      # Step 3: Generate binstubs
      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop

      # Step 4: Security audit dependencies
      - name: Security audit dependencies
        run: bin/bundler-audit --update

      # Step 5: Security audit application code
      - name: Security audit application code
        run: bundle exec brakeman -q -w2

      # Step 6: Lint Ruby files
      - name: Lint Ruby files
        run: bundle exec rubocop --auto-correct-all --disable-uncorrectable
